GP-233 Create the SC for storing GRMX exchange rate
Gaimin-io-Limited/gmrx-vesting pull request #6
Opened 2024-04-25 08:11 UTC by WilliamVoitsekhovskyi

2024-05-01 10:51 UTC, Yurii-Didur commented on contracts/GmrxRate.sol
> +pragma solidity ^0.8.0;
думаю було б непогано затаргетити якусь вищу конкретну версія, наприклад 0.8.24

2024-05-01 10:51 UTC, Yurii-Didur commented on contracts/GmrxRate.sol
> +import "@openzeppelin/contracts/access/Ownable.sol";
ну і тоді відповідно змінити трохи імпорт на import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

2024-05-01 10:52 UTC, Yurii-Didur requested changes
Please see the comments

2024-05-01 14:00 UTC, Yurii-Didur approved these changes

2024-05-02 12:36 UTC, vova-yatsyk-theraven approved these changes

2024-05-02 13:22 UTC, merged